export function formatDate(dateString) {
  if (!dateString) return new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const date = new Date(dateString + 'T00:00:00');
  return date.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
}

export const SERVICE_PRIVACY_LINKS = {
  // Payment
  'Stripe': 'https://stripe.com/privacy',
  'Paddle': 'https://www.paddle.com/legal/privacy',
  'PayPal': 'https://www.paypal.com/webapps/mpp/ua/privacy-full',
  'Lemon Squeezy': 'https://www.lemonsqueezy.com/privacy',
  // Analytics
  'Google Analytics': 'https://policies.google.com/privacy',
  'Plausible': 'https://plausible.io/privacy',
  'Fathom': 'https://usefathom.com/privacy',
  'PostHog': 'https://posthog.com/privacy',
  'Mixpanel': 'https://mixpanel.com/legal/privacy-policy',
  // Email
  'SendGrid': 'https://www.twilio.com/en-us/legal/privacy',
  'Mailchimp': 'https://mailchimp.com/legal/privacy/',
  'Resend': 'https://resend.com/legal/privacy-policy',
  'Postmark': 'https://postmarkapp.com/privacy-policy',
  'ConvertKit': 'https://kit.com/privacy',
  // Auth
  'Auth0': 'https://auth0.com/privacy',
  'Clerk': 'https://clerk.com/legal/privacy',
  'Supabase Auth': 'https://supabase.com/privacy',
  'Firebase Auth': 'https://firebase.google.com/support/privacy',
  // Hosting
  'Vercel': 'https://vercel.com/legal/privacy-policy',
  'AWS': 'https://aws.amazon.com/privacy/',
  'Google Cloud': 'https://policies.google.com/privacy',
  'Railway': 'https://railway.com/legal/privacy',
  'Fly.io': 'https://fly.io/legal/privacy-policy/',
  // Error tracking
  'Sentry': 'https://sentry.io/privacy/',
  'LogRocket': 'https://logrocket.com/privacy/',
  'Datadog': 'https://www.datadoghq.com/legal/privacy/',
  // AI
  'OpenAI': 'https://openai.com/policies/privacy-policy',
  'Anthropic': 'https://www.anthropic.com/privacy',
  'Google AI': 'https://policies.google.com/privacy',
  'Mistral': 'https://mistral.ai/terms/#privacy-policy',
  'Cohere': 'https://cohere.com/privacy',
};

export function getAllSelectedServices(data) {
  const services = [];
  const categories = {
    'Payment Processing': data.paymentServices,
    'Analytics': data.analyticsServices,
    'Email': data.emailServices,
    'Authentication': data.authServices,
    'Hosting': data.hostingServices,
    'Error Tracking': data.errorTrackingServices,
  };

  for (const [category, selected] of Object.entries(categories)) {
    if (selected && selected.length > 0) {
      const filtered = selected.filter(s => s !== 'None' && s !== 'Other' && s !== 'Custom');
      if (filtered.length > 0) {
        services.push({ category, services: filtered });
      }
    }
  }
  return services;
}

export function includesEU(data) {
  return data.userLocations?.includes('European Union') || data.userLocations?.includes('Worldwide');
}

export function includesUS(data) {
  return data.userLocations?.includes('United States') || data.userLocations?.includes('Worldwide');
}

export function getJurisdictionText(location) {
  const map = {
    'United States': 'the State of Delaware, United States',
    'European Union': 'the laws of the European Union',
    'United Kingdom': 'the laws of England and Wales',
    'Canada': 'the laws of the Province of Ontario, Canada',
    'Australia': 'the laws of New South Wales, Australia',
    'Other': 'applicable local law',
  };
  return map[location] || 'applicable local law';
}

export const LEGAL_DISCLAIMER = `---

*This document was generated by ShipLegal and is provided for informational purposes only. It does not constitute legal advice. We recommend consulting with a qualified attorney for your specific needs.*`;
